<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Registro</title>
    <link rel="stylesheet" href="../css/stylewall.css">
</head>

<body>
    <h1>Registro</h1>
    <form class="form" action="registration.php" method="post">
        <label>Usuario:</label>
        <input type="text" name="username"/><br />
        <label>Contraseña:</label>
        <input type="password" name="password"/><br/>
        <input type="submit" value=" Registrarse "/><br />
    </form>
    <p> Volver a la página de login</p>
    <form class="form" action="index.php" method="POST">
        <input type="submit" value="volver">
    </form>
</body>

</html>
